sed -i "s/saveFirestoreDoc('members', updatedMbr)/AppService.updateMember(updatedMbr)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('members', memberId)/AppService.deleteMember(memberId)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('advocacyCases', newCase)/AppService.addAdvocacy(newCase)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('advocacyCases', updatedCase)/AppService.updateAdvocacy(updatedCase)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('advocacyCases', id)/AppService.deleteAdvocacy(id)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sickVisits', newVisit)/AppService.addSickVisit(newVisit)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sickVisits', updatedVisit)/AppService.updateSickVisit(updatedVisit)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('sickVisits', visitId)/AppService.deleteSickVisit(visitId)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('agendas', newAgd)/AppService.addAgenda(newAgd)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('agendas', updatedAgd)/AppService.updateAgenda(updatedAgd)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('agendas', agendaId)/AppService.deleteAgenda(agendaId)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('fundraising', newCamp)/AppService.addFundraising(newCamp)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('fundraising', updatedCamp)/AppService.updateFundraising(updatedCamp)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('fundraising', id)/AppService.deleteFundraising(id)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sembakoEvents', newEvent)/AppService.addSembakoEvent(newEvent)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sembakoClaims', updatedClaim)/AppService.updateSembakoClaim(updatedClaim)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sembakoEvents', updatedEvent)/AppService.updateSembakoEvent(updatedEvent)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('sembakoEvents', updatedEv)/AppService.updateSembakoEvent(updatedEv)/g" src/App.tsx
sed -i "s/saveFullCollection('sembakoClaims', updatedClaims)/AppService.saveAllSembakoClaims(updatedClaims)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('vehicleLogs', newLog)/AppService.addVehicleLog(newLog)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('vehicleLogs', updatedLog)/AppService.updateVehicleLog(updatedLog)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('vehicleLogs', id)/AppService.deleteVehicleLog(id)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('financeRecords', cleanRecord)/AppService.addFinanceRecord(cleanRecord)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('financeRecords', id)/AppService.deleteFinanceRecord(id)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('users', userToSave)/AppService.addUser(userToSave)/g" src/App.tsx
sed -i "s/deleteFirestoreDoc('users', userId)/AppService.deleteUser(userId)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('users', updatedUser)/AppService.updateUser(updatedUser)/g" src/App.tsx
sed -i "s/saveFirestoreDoc('members', updatedMember)/AppService.updateMember(updatedMember)/g" src/App.tsx
sed -i "s/saveFullCollection('members', importedMembers)/AppService.saveAllMembers(importedMembers)/g" src/App.tsx
